retrieve_09S2y000000iMwPEAU/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_09S2y000000iMwPEAU/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>email</label>
        <type>Email</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_09S2y000000iMwPEAU/classes/StudentDetailsController.cls
public class StudentDetailsController 
{
 
    public Id parentId{get;set;}
    public String pdfName {get;set;}
    public Student__c myStudent{get;set;}
    
    public StudentController( )
    {
        
        Id studentId = Apexpages.CurrentPage().getParameters().get('Id');
        myStudent = [SELECT Id, Class__c, Name, DOB__c, Class__r.Name, email__c FROM Student__c WHERE Id =: studentId LIMIT 1 ][0];
        parentId = myStudent.Id;
        pdfName = myStudent.Id;
       
    }
    
    public void savePdf()
    {
        
        PageReference pdf = ApexPages.currentPage();
        
   		Attachment attach = new Attachment();
    	Blob body;
    	try 
        {
        
    	body = pdf.getContent();
    		
    	} catch (VisualforceException e) 
        {
    	body = Blob.valueOf('Some Text');
   		}
        
		attach.Body = body;
        attach.Name = pdfName;
        attach.IsPrivate = false;
   		attach.ParentId = parentId;
        List<Attachment> attachments = [SELECT Id FROM Attachment WHERE Name =: pdfName];
        
        if(attachments.size() > 0)
            delete attachments[0];

   		insert attach;
    }
}