retrieve_09S2y000000iMwPEAU/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Custom_Status__c</fullName>
        <label>Custom Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Close</fullName>
                </value>
                <value>
                    <fullName>Reset</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MaxSize__c</fullName>
        <label>MaxSize</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MyCount__c</fullName>
        <label>MyCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_09S2y000000iMwPEAU/classes/ManageClassController.cls
public class ManageClassController 
{
    public Id classId{get;set;}
    public boolean render{get;set;}
    public class__c selectedClass{get;set;}

    public manageClassController() 
    {
        render = false;
    }
 
    public list<class__c> getClassRecList() 
    {
        List<class__c> classRecList = [SELECT Name, MaxSize__c, MyCount__c, Custom_Status__c FROM class__c];
        return classRecList;
    }
    
    public void editClass() 
    {
        selectedClass = [SELECT Name, MaxSize__c, MyCount__c, Custom_Status__c FROM Class__c WHERE Id =: classId];
        render = true;
    }
    
    public void updateClass() 
    {
        update selectedClass;
        render = false;
    }
   
    public void deleteClass() 
    {
        selectedClass = [SELECT Name, MaxSize__c, MyCount__c, Custom_Status__c FROM Class__c WHERE Id =: classId];
        render = false;
        delete selectedClass;
    }
}