Module 16 - Enterprise Pattern/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Price_Per_Unit__c</fullName>
        <label>Price Per Unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity_Available__c</fullName>
        <label>Quantity Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Module 16 - Enterprise Pattern/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <summarizedField>Purchase_Order_Line_Item__c.Total_Price__c</summarizedField>
        <summaryForeignKey>Purchase_Order_Line_Item__c.Purchase_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Module 16 - Enterprise Pattern/objects/Purchase_Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Purchase Order Line Items</relationshipLabel>
        <relationshipName>Purchase_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Line Items</relationshipLabel>
        <relationshipName>Purchase_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Purchase Order Line Item</label>
    <nameField>
        <label>Purchase Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Module 16 - Enterprise Pattern/classes/checkoutService.cls
public with sharing class checkoutService 
{
     public static Purchase_Order__c placeOrder(List<Product2> checkoutItems)
     {
        fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
            new List<SObjectType> { Product2.SObjectType, Purchase_Order__c.SObjectType, Purchase_Order_Line_Item__c.SObjectType  }
        );

        Purchase_Order__c purchaseOrder = new Purchase_Order__c(Name = 'Harshit', Order_Status__c = 'Pending');
        insert purchaseOrder;
        //uow.registerNew(purchaseOrder);
        //List<Purchase_Order_Line_Item__c> purchaseOrderLineItemList = new List<Purchase_Order_Line_Item__c>();
        //List<Product2> productList = new List<Product2>();
        for(Product2 product : checkoutItems) 
        {
            uow.registerNew(new Purchase_Order_Line_Item__c(Purchase_Order__c = purchaseOrder.Id,
                                                                       Product__c = product.Id,
                                                                       Quantity__c = product.Quantity__c,
                                                                       Total_Price__c = product.Quantity__c * product.Price_Per_Unit__c));
            product.Quantity__c = product.Quantity_Available__c;
            //productList.add(product);
            uow.registerDirty(product);
        }
        //update productList;        
        //insert purchaseOrderLineItemList; 
        uow.commitwork(); 
        return purchaseOrder;


     }
}