Module 16 - Enterprise Pattern/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <summarizedField>Purchase_Order_Line_Item__c.Total_Price__c</summarizedField>
        <summaryForeignKey>Purchase_Order_Line_Item__c.Purchase_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Module 16 - Enterprise Pattern/classes/PurchaseOrderSelector.cls
public class PurchaseOrderSelector extends fflib_SObjectSelector
{
    public List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField>{Purchase_Order__c.Id, Purchase_Order__c.Total_Price__c, Purchase_Order__c.Order_Status__c};
    }

    public Schema.SObjectType getSObjectType()
    {
        return Purchase_Order__c.sObjectType;
    }
    
    public static List<Purchase_Order__c> getPurchaseOrders()
    {
        return [SELECT Id, Total_Price__c, Order_Status__c FROM Purchase_Order__c];

    }

    public static List<Purchase_Order__c> getPurchaseOrdersWithLimit(Integer limitValue)
    {
        return [SELECT Id, Total_Price__c, Order_Status__c FROM Purchase_Order__c LIMIT : limitValue];

    }

    public static Integer getPurchaseOrderCount()
    {
        return [SELECT count() FROM Purchase_Order__c];

    }

    public static List<Purchase_Order__c> getPurchaseOrdersByOffset(Integer limitValue, Integer offsetValue)
    {
        return [SELECT Id, Total_Price__c, Order_Status__c FROM Purchase_Order__c LIMIT : limitValue OFFSET : offsetValue];
    }

}